    spring.application.name=game-stats-platform

#SPRING_DATA_MONGODB_URI = mongodb+srv://hanelmislimi_db_user:Samsungg00@cluster0.uwc6tti.mongodb.net/game_stats_db?retryWrites=true&w=majority

#   spring.data.mongodb.uri=mongodb+srv://hanelmislimi_db_user:Samsungg00@cluster0.uwc6tti.mongodb.net/game_stats_db?retryWrites=true&w=majority


# spring.data.mongodb.uri=mongodb://localhost:27017/game_stats_db

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

    server.port=8080

    springdoc.api-docs.path=/v3/api-docs

    jwt.secret=mySuperSecretKeyForJwtAuthentication123456789

    jwt.expiration=86400000

pubg.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiYzQ5ZTg5MC0zNDYyLTAxM2YtZjE3NC03NjQ4ZmM0MTg5YjMiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNzc5MDUyMjIwLCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6ImdhbWUtc3RhdHMtcGxhIn0.FIaF1Wd7WrPH8R58n2E0UqHksJXRjn04sq5334xtwVM

# =========================
# APPLICATION
# =========================
app.frontend-url=https://game-stats-platform.netlify.app
app.password-reset.expiration-minutes=15

# =========================
# GMAIL
# =========================



resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL}




riot.api.key=${RIOT_API_KEY}

riot.lol.platform=euw1.api.riotgames.com
riot.lol.region=europe.api.riotgames.com