    spring.application.name=game-stats-platform

#SPRING_DATA_MONGODB_URI = mongodb+srv://hanelmislimi_db_user:Samsungg00@cluster0.uwc6tti.mongodb.net/game_stats_db?retryWrites=true&w=majority

#   spring.data.mongodb.uri=mongodb+srv://hanelmislimi_db_user:Samsungg00@cluster0.uwc6tti.mongodb.net/game_stats_db?retryWrites=true&w=majority


# spring.data.mongodb.uri=mongodb://localhost:27017/game_stats_db

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

    server.port=8080

    springdoc.api-docs.path=/v3/api-docs

    jwt.secret=mySuperSecretKeyForJwtAuthentication123456789

    jwt.expiration=86400000

pubg.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiYzQ5ZTg5MC0zNDYyLTAxM2YtZjE3NC03NjQ4ZmM0MTg5YjMiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNzc5MDUyMjIwLCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6ImdhbWUtc3RhdHMtcGxhIn0.FIaF1Wd7WrPH8R58n2E0UqHksJXRjn04sq5334xtwVM

# =========================
# APPLICATION
# =========================
app.frontend-url=http://localhost:8080
app.password-reset.expiration-minutes=15

# =========================
# GMAIL
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true.smtp.starttls.required=truecalhost:8080